#!/usr/bin/env node
/**
 * MCP Superstack - Codex CLI Setup Script
 *
 * Configures MCP servers for OpenAI Codex CLI.
 * Handles the timeout issue with remote MCP servers.
 *
 * Usage: npm run setup:codex
 */

import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const HOME = os.homedir();
const CODEX_DIR = path.join(HOME, '.codex');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

function getNodePath() {
  // Try common Node.js paths
  const paths = [
    '/opt/homebrew/bin/node',  // macOS Homebrew ARM
    '/usr/local/bin/node',     // macOS Homebrew Intel
    '/usr/bin/node',           // Linux
    process.execPath,          // Current Node.js
  ];

  for (const p of paths) {
    if (fs.existsSync(p)) {
      return p;
    }
  }

  return process.execPath;
}

async function main() {
  console.log('\n🚀 MCP Superstack - Codex CLI Setup\n');
  console.log('This will configure MCP servers for Codex CLI.\n');

  // Check for existing .env
  const envPath = path.join(ROOT, '.env');
  let config = {};

  if (fs.existsSync(envPath)) {
    console.log('📄 Found existing .env file, loading configuration...\n');
    const envContent = fs.readFileSync(envPath, 'utf-8');
    envContent.split('\n').forEach(line => {
      const match = line.match(/^([^#=]+)=(.*)$/);
      if (match) {
        config[match[1].trim()] = match[2].trim();
      }
    });
  } else {
    console.log('⚠️  No .env file found. Run "npm run setup" first.\n');
    console.log('Collecting minimal configuration...\n');

    config.POLYDEV_USER_TOKEN = await question('Polydev User Token: ');
    config.EXA_API_KEY = await question('Exa API Key: ');
    config.GITHUB_TOKEN = await question('GitHub Personal Access Token: ');
    config.ALLOWED_DIRECTORY = await question(`Allowed Directory [${HOME}/Documents]: `) || `${HOME}/Documents`;
  }

  rl.close();

  // Create .codex directory
  if (!fs.existsSync(CODEX_DIR)) {
    fs.mkdirSync(CODEX_DIR, { recursive: true });
    console.log('✅ Created ~/.codex/ directory');
  }

  // Copy polydev wrapper
  const wrapperSrc = path.join(ROOT, 'templates/codex-cli/polydev-stdio-wrapper.js');
  const wrapperDst = path.join(CODEX_DIR, 'polydev-stdio-wrapper.js');

  if (fs.existsSync(wrapperSrc)) {
    fs.copyFileSync(wrapperSrc, wrapperDst);
    fs.chmodSync(wrapperDst, 0o755);
    console.log('✅ Installed polydev-stdio-wrapper.js');
  }

  // Generate config.toml
  const nodePath = getNodePath();
  const username = os.userInfo().username;

  let configToml = `####################################
# Codex CLI MCP Configuration
# Generated by mcp-superstack setup-codex
####################################

####################################
# Projects trust
####################################
[projects."${config.ALLOWED_DIRECTORY || HOME + '/Documents'}"]
trust_level = "trusted"

####################################
# MCP servers
####################################

`;

  // Exa
  if (config.EXA_API_KEY) {
    configToml += `# Exa - Semantic web search
[mcp_servers.exa]
command = "mcp-proxy"
args = ["https://mcp.exa.ai/mcp?exaApiKey=${config.EXA_API_KEY}", "--transport", "streamablehttp"]
env = {}

`;
  }

  // Memory
  configToml += `# Memory - Knowledge graph
[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]
env = {}

`;

  // Supabase
  if (config.SUPABASE_ACCESS_TOKEN && config.SUPABASE_PROJECT_REF) {
    configToml += `# Supabase - PostgreSQL database
[mcp_servers.supabase]
command = "npx"
args = ["-y", "@supabase/mcp-server-supabase@latest", "--access-token", "${config.SUPABASE_ACCESS_TOKEN}", "--project-ref", "${config.SUPABASE_PROJECT_REF}"]
env = { SUPABASE_URL = "${config.SUPABASE_URL || ''}", SUPABASE_ANON_KEY = "${config.SUPABASE_ANON_KEY || ''}", SUPABASE_SERVICE_ROLE_KEY = "${config.SUPABASE_SERVICE_ROLE_KEY || ''}" }

`;
  }

  // Sequential Thinking
  configToml += `# Sequential Thinking - Step-by-step reasoning
[mcp_servers.seq_thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
env = {}

`;

  // Filesystem
  configToml += `# Filesystem - File operations
[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "${config.ALLOWED_DIRECTORY || HOME + '/Documents'}"]
env = {}

`;

  // GitHub
  if (config.GITHUB_TOKEN) {
    configToml += `# GitHub - Repository, issues, PRs
[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
env = { GITHUB_PERSONAL_ACCESS_TOKEN = "${config.GITHUB_TOKEN}" }

`;
  }

  // Vercel
  if (config.VERCEL_TOKEN && config.VERCEL_TEAM && config.VERCEL_PROJECT) {
    configToml += `# Vercel - Deployment management
[mcp_servers.vercel]
command = "mcp-proxy"
args = ["https://mcp.vercel.com/${config.VERCEL_TEAM}/${config.VERCEL_PROJECT}", "--transport", "streamablehttp", "-H", "Authorization", "Bearer ${config.VERCEL_TOKEN}"]
env = {}

`;
  }

  // Polydev (uses local wrapper for fast handshake)
  if (config.POLYDEV_USER_TOKEN) {
    configToml += `# Polydev - Multi-model AI (uses local wrapper for fast handshake)
# IMPORTANT: Uses local wrapper to fix Codex timeout issue
[mcp_servers.polydev]
command = "${nodePath}"
args = ["${wrapperDst}"]
env = { POLYDEV_USER_TOKEN = "${config.POLYDEV_USER_TOKEN}" }

`;
  }

  // Context7
  configToml += `# Context7 - Library documentation
[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]
env = {}

`;

  // DeepWiki
  configToml += `# DeepWiki - Wikipedia search
[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-deepwiki@latest"]
env = {}

`;

  // Upstash
  if (config.UPSTASH_EMAIL && config.UPSTASH_API_KEY) {
    configToml += `# Upstash - Redis cache
[mcp_servers.upstash]
command = "npx"
args = ["-y", "@upstash/mcp-server", "run", "${config.UPSTASH_EMAIL}", "${config.UPSTASH_API_KEY}"]
env = {}

`;
  }

  // Write config.toml
  const configPath = path.join(CODEX_DIR, 'config.toml');

  if (fs.existsSync(configPath)) {
    const backupPath = path.join(CODEX_DIR, 'config.toml.backup');
    fs.copyFileSync(configPath, backupPath);
    console.log('📄 Backed up existing config.toml');
  }

  fs.writeFileSync(configPath, configToml);
  console.log('✅ Generated ~/.codex/config.toml');

  console.log('\n🎉 Codex CLI setup complete!\n');
  console.log('Configured MCP servers:');

  const servers = [];
  if (config.EXA_API_KEY) servers.push('  - exa (web search)');
  servers.push('  - memory (knowledge graph)');
  if (config.SUPABASE_ACCESS_TOKEN) servers.push('  - supabase (database)');
  servers.push('  - seq_thinking (reasoning)');
  servers.push('  - filesystem (file ops)');
  if (config.GITHUB_TOKEN) servers.push('  - github (repos/issues)');
  if (config.VERCEL_TOKEN) servers.push('  - vercel (deployment)');
  if (config.POLYDEV_USER_TOKEN) servers.push('  - polydev (multi-model AI)');
  servers.push('  - context7 (library docs)');
  servers.push('  - deepwiki (wikipedia)');
  if (config.UPSTASH_API_KEY) servers.push('  - upstash (redis)');

  console.log(servers.join('\n'));

  console.log('\nTest with: codex --help');
  console.log('');
}

main().catch(console.error);
