#!/usr/bin/env node
/**
 * MCP Superstack Setup Script
 *
 * Automated setup for Claude Code integration.
 * Creates .env file from template and installs dependencies.
 *
 * Usage: npm run setup
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n🚀 MCP Superstack Setup\n');
  console.log('This will configure your MCP servers for Claude Code.\n');

  // Check if .env exists
  const envPath = path.join(ROOT, '.env');
  const envExamplePath = path.join(ROOT, '.env.example');

  if (fs.existsSync(envPath)) {
    const overwrite = await question('.env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\nKeeping existing .env file.');
      rl.close();
      return;
    }
  }

  console.log('\nPlease provide your API keys (press Enter to skip):\n');

  const config = {};

  // Essential keys
  config.POLYDEV_USER_TOKEN = await question('Polydev User Token: ');
  config.EXA_API_KEY = await question('Exa API Key: ');
  config.GITHUB_TOKEN = await question('GitHub Personal Access Token: ');

  // Supabase
  console.log('\n--- Supabase (optional) ---');
  config.SUPABASE_ACCESS_TOKEN = await question('Supabase Access Token: ');
  config.SUPABASE_PROJECT_REF = await question('Supabase Project Ref: ');
  config.SUPABASE_URL = await question('Supabase URL: ');
  config.SUPABASE_ANON_KEY = await question('Supabase Anon Key: ');
  config.SUPABASE_SERVICE_ROLE_KEY = await question('Supabase Service Role Key: ');

  // Infrastructure
  console.log('\n--- Infrastructure (optional) ---');
  config.VERCEL_TOKEN = await question('Vercel Token: ');
  config.VERCEL_TEAM = await question('Vercel Team: ');
  config.VERCEL_PROJECT = await question('Vercel Project: ');
  config.STRIPE_API_KEY = await question('Stripe API Key: ');
  config.RESEND_API_KEY = await question('Resend API Key: ');

  // Upstash
  console.log('\n--- Upstash Redis (optional) ---');
  config.UPSTASH_EMAIL = await question('Upstash Email: ');
  config.UPSTASH_API_KEY = await question('Upstash API Key: ');

  // Perplexity
  config.PERPLEXITY_API_KEY = await question('\nPerplexity API Key (optional): ');

  // Filesystem
  const defaultAllowedDir = process.env.HOME + '/Documents';
  config.ALLOWED_DIRECTORY = await question(`\nAllowed Directory [${defaultAllowedDir}]: `) || defaultAllowedDir;

  rl.close();

  // Generate .env content
  let envContent = `# MCP Superstack Configuration
# Generated by setup script

# ============================================
# Essential Services
# ============================================

# Polydev - Multi-model AI perspectives
POLYDEV_USER_TOKEN=${config.POLYDEV_USER_TOKEN || ''}

# Exa - Semantic web search
EXA_API_KEY=${config.EXA_API_KEY || ''}

# GitHub - Repository management
GITHUB_TOKEN=${config.GITHUB_TOKEN || ''}

# ============================================
# Supabase - PostgreSQL Database
# ============================================
SUPABASE_ACCESS_TOKEN=${config.SUPABASE_ACCESS_TOKEN || ''}
SUPABASE_PROJECT_REF=${config.SUPABASE_PROJECT_REF || ''}
SUPABASE_URL=${config.SUPABASE_URL || ''}
SUPABASE_ANON_KEY=${config.SUPABASE_ANON_KEY || ''}
SUPABASE_SERVICE_ROLE_KEY=${config.SUPABASE_SERVICE_ROLE_KEY || ''}

# ============================================
# Infrastructure Services
# ============================================

# Vercel - Deployment
VERCEL_TOKEN=${config.VERCEL_TOKEN || ''}
VERCEL_TEAM=${config.VERCEL_TEAM || ''}
VERCEL_PROJECT=${config.VERCEL_PROJECT || ''}

# Stripe - Payments
STRIPE_API_KEY=${config.STRIPE_API_KEY || ''}

# Resend - Email
RESEND_API_KEY=${config.RESEND_API_KEY || ''}

# ============================================
# Cache & Storage
# ============================================

# Upstash Redis
UPSTASH_EMAIL=${config.UPSTASH_EMAIL || ''}
UPSTASH_API_KEY=${config.UPSTASH_API_KEY || ''}

# ============================================
# Additional AI Services
# ============================================

# Perplexity - AI-powered search
PERPLEXITY_API_KEY=${config.PERPLEXITY_API_KEY || ''}

# ============================================
# Filesystem Access
# ============================================
ALLOWED_DIRECTORY=${config.ALLOWED_DIRECTORY || ''}
`;

  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ Created .env file');

  // Copy CLAUDE.md templates
  const claudeGlobalSrc = path.join(ROOT, 'templates/claude-code/CLAUDE.global.md');
  const claudeGlobalDst = path.join(process.env.HOME, '.claude/CLAUDE.md');

  if (fs.existsSync(claudeGlobalSrc)) {
    const claudeDir = path.dirname(claudeGlobalDst);
    if (!fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }

    if (!fs.existsSync(claudeGlobalDst)) {
      fs.copyFileSync(claudeGlobalSrc, claudeGlobalDst);
      console.log('✅ Copied CLAUDE.md to ~/.claude/');
    } else {
      console.log('⚠️  ~/.claude/CLAUDE.md already exists - skipping');
    }
  }

  console.log('\n🎉 Setup complete!\n');
  console.log('Next steps:');
  console.log('  1. Run: npm install');
  console.log('  2. Run: npm run build');
  console.log('  3. Import in your code: import { exa, polydev } from "mcp-superstack"');
  console.log('\nFor Codex CLI setup, run: npm run setup:codex\n');
}

main().catch(console.error);
